[[project]]
repo = "SpicyLyricTranslator"

[[project]]
repo = "SpicyThemes"

[[project]]
repo = "SpotifyModernEQ"

[[project]]
repo = "QueueETA"
summary = "See Spotify queue time."

[[project]]
repo = "CarX-Blender-Tools"

