[[project]]
repo = "SpicyLyricTranslator"

[[project]]
repo = "SpicyThemes"

[[project]]
repo = "SpotifyModernEQ"

[[project]]
repo = "QueueETA"

[[project]]
repo = "CarX-Blender-Tools"

[[project]]
repo = "NightyScripts"
summary = "Automation scripts for the Nighty selfbot."
